language: go

branches:
  only:
  - master
  - develop
  - staging
  - tmup
  - lity
  - /^v.*$/

services:
  - docker

addons:
  hosts:
  - node-1
  - node-2
  - node-3
  - node-4
  - node-5
  - node-6

before_install:
  - echo Checking whether $ECHOIN_COMMIT_RANGE changed only docs
  - |
    if [ -z "$ECHOIN_TAG" ]; then
      git diff --name-only $ECHOIN_COMMIT_RANGE | grep -qvE '(\.md$|^(docs)/)' || {
        echo "Only docs were updated, stopping build process."
        exit
      }
    fi

install:
  - ". $HOME/.nvm/nvm.sh"
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - make docker_image
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  - TAG=$ECHOIN_BRANCH make push_tag_image ;
  - |
    if [ -z "$ECHOIN_TAG" ]; then
      ./test/integration/test.sh
    fi

after_success:
  - if [[ "$ECHOIN_BRANCH" == "master" ]]; then
      make push_image ;
    fi

after_failure:
  - curl -i "http://localhost:26657/dump_consensus_state"
  - >
    curl -X POST http://localhost:8545
    -H 'Content-Type: application/json'
    -d '{"jsonrpc":"2.0","id":1,"method":"ec_queryValidators", "params": [0]}'
  - cd ~/volumes/testnet/echoin/scripts && docker-compose logs -t --tail 50

before_deploy:
  - BUILD_TAG=$ECHOIN_TAG make dist
  - |
    if [[ "$ECHOIN_TAG" == "vStaging" ]]; then
      export BODY=release for staging
    elif [[ "$ECHOIN_TAG" == "vTestnet" ]]; then
      export BODY=release for testnet
    else
      export BODY=https://github.com/blockservice/echoin/blob/develop/CHANGELOG.md#${ECHOIN_TAG//.}
    fi

deploy:
  provider: releases
  overwrite: true
  api-key:
    secure: iIaBQLDBPzi95sIt36XaOaSrD7hwB/dUxAfpCeFLoFqdGNsGZhaPp4XfW8UghwqNlUF9spW1Ri8uOMF2Ig3FBTmeL/GELJl8pSJwhjb3Ra3p+kGg5eKyIZMvK1m9uoXBBMlMnjPhS9h0Z8bOpXLiEpQASV6nnJ0KE2N39ff3jBKShWDNWejOAYBTNNJ9N7GF8gh6z/xLwZ82nLWmOYGkwrEA9fH93IzguehmUyD2bbU66un0QrRfUCQ8xruxTENZ9ATz7GqOrqYe0L+IUbmK10VIYlJ1S7PcWvBSY4J4nslLnpFw2m+/3Zt2Cq/xaCLs7bmOlMie0AEbtyGamXxEIlNcIeWeOIyXv0k4yqGm5+IUl2scggDXGmysXCjwbQbLnPbHXo0sYlNMUr4WkH2LlPENT9r4mQGDwOYkrwt0ZlU9n+67IpgTBuBqd//khzmnjdDPleWZyr6fOfjfA8uBGbcO8fANyJOAzoPQQtKp7crzhyt2aVZB2M7JAGsJCr1TUZl9Y2KgAKkCQnpwBAZdntUB0DvodBFqVG61zaH4yY6k+5kiHC+kZ9gSqoh3gMoMlANRqaoIB+3IVf1TXWyVx4dp11RGCBxNmccvA1h+RsI8GXsCPSLYINiQLKWUl3jmNYbmQKK7TyWWl/soCTco6NnyivLp6cxbDi0zqy5xTDc=
  skip_cleanup: true
  file_glob: true
  file: "build/dist/*.zip"
  name: Echoin $ECHOIN_TAG
  body: $BODY
  on:
    repo: blockservice/echoin
    tags: true
